"""Paragliding takeoffs, as committed data.

Generated by `meteo.sources.write` from ParaglidingEarth on 2026-09-23, for the
takeoffs `meteo.sources.CHOSEN` names, in its order:
    https://www.paraglidingearth.com/api/geojson/getCountrySites.php?iso={CZ,SK,DE,IT,SI}&style=detailled

`winds` is ParaglidingEarth's own suitability per octant, N first and clockwise:
0 unflyable, 1 marginal, 2 good. An empty list means the site records none, and
the page then refuses to judge it against the forecast rather than guessing.
"""

SOURCE = "https://www.paraglidingearth.com/api/geojson/getCountrySites.php?iso={CZ,SK,DE,IT,SI}&style=detailled"
FETCHED = "2026-09-23"
ATTRIBUTION = "Takeoffs from ParaglidingEarth, CC BY-SA"
OCTANTS = ("N", "NE", "E", "SE", "S", "SW", "W", "NW")

SITES = [
    {"name": 'Raná', "country": 'CZ', "lat": 50.4075, "lon": 13.7715, "alt": 426, "winds": [2, 0, 0, 2, 2, 0, 0, 2], "id": 10099},
    {"name": 'Krupka', "country": 'CZ', "lat": 50.6964, "lon": 13.8769, "alt": 644, "winds": [0, 0, 0, 1, 2, 1, 0, 0], "id": 6737},
    {"name": 'Kozákov', "country": 'CZ', "lat": 50.5933, "lon": 15.2632, "alt": 737, "winds": [0, 0, 0, 1, 2, 2, 2, 1], "id": 7197},
    {"name": 'Černá hora', "country": 'CZ', "lat": 50.6496, "lon": 15.74, "alt": 1254, "winds": [0, 0, 0, 1, 2, 1, 0, 0], "id": 7188},
    {"name": 'Dolní Morava', "country": 'CZ', "lat": 50.1544, "lon": 16.8377, "alt": 1228, "winds": [0, 0, 0, 1, 2, 1, 0, 0], "id": 21878},
    {"name": 'Velký Lopeník', "country": 'SK', "lat": 48.9152, "lon": 17.7824, "alt": 866, "winds": [0, 0, 1, 2, 2, 2, 1, 0], "id": 10270},
    {"name": 'Martinské hole', "country": 'SK', "lat": 49.0963, "lon": 18.8238, "alt": 1433, "winds": [], "id": 22106},
    {"name": 'Pálava - Děvín', "country": 'CZ', "lat": 48.8674, "lon": 16.6523, "alt": 504, "winds": [0, 0, 2, 2, 0, 0, 0, 0], "id": 22931},
    {"name": 'Všechov', "country": 'CZ', "lat": 49.4379, "lon": 14.6222, "alt": 489, "winds": [1, 1, 1, 2, 1, 1, 1, 2], "id": 10333},
    {"name": 'Doubrava', "country": 'CZ', "lat": 49.4328, "lon": 13.2028, "alt": 715, "winds": [0, 0, 0, 0, 0, 0, 2, 0], "id": 12436},
    {"name": 'Hausstein', "country": 'DE', "lat": 48.8712, "lon": 13.0729, "alt": 880, "winds": [0, 0, 0, 2, 0, 0, 0, 0], "id": 8590},
    {"name": 'Bassano', "country": 'IT', "lat": 45.8238, "lon": 11.7694, "alt": 865, "winds": [0, 0, 0, 1, 2, 1, 0, 0], "id": 9200},
    {"name": 'Col Rodella', "country": 'IT', "lat": 46.4972, "lon": 11.7535, "alt": 2360, "winds": [2, 1, 0, 1, 2, 2, 1, 1], "id": 7243},
    {"name": 'Meduno', "country": 'IT', "lat": 46.2306, "lon": 12.8069, "alt": 983, "winds": [0, 0, 0, 0, 1, 2, 1, 0], "id": 19791},
    {"name": 'Kobala', "country": 'SI', "lat": 46.1805, "lon": 13.7791, "alt": 1061, "winds": [0, 0, 2, 1, 1, 1, 2, 0], "id": 7183},
]
