"""Where the site list comes from, and the script that regenerates it.

One source, and it is not scraped: ParaglidingEarth publishes a documented GeoJSON API
per country, and its records carry the two things this page needs and a weather site
cannot know — where the takeoff is, and **which wind directions it works in**. That
second field is what turns a forecast into an answer: 20 km/h from the north-west is a
good day at one hill and unflyable at the next one along.

The list is fetched once and committed as `sites.py` rather than fetched at build time.
Takeoffs do not move, the file is small, and a page that cannot be built because a
community database is down is a bad trade. `--refresh-sites` rewrites it, and the header
it writes records where and when, so the next person can tell how stale it is.
"""

from __future__ import annotations

import datetime as dt
import json
import urllib.request
from pathlib import Path

ENDPOINT = ("https://www.paraglidingearth.com/api/geojson/getCountrySites.php"
            "?iso={iso}&style=detailled")
ATTRIBUTION = "Takeoffs from ParaglidingEarth, CC BY-SA"
OCTANTS = ("N", "NE", "E", "SE", "S", "SW", "W", "NW")
TIMEOUT = 60


def fetch(iso: str = "CZ") -> list[dict]:
    """Every published takeoff in the country, as this module's own records."""
    url = ENDPOINT.format(iso=iso)
    with urllib.request.urlopen(url, timeout=TIMEOUT) as response:
        payload = json.loads(response.read().decode("utf-8"))

    sites = []
    for feature in payload.get("features", []):
        properties = feature.get("properties", {})
        lon, lat = feature["geometry"]["coordinates"][:2]
        name = (properties.get("name") or "").strip()
        if not name:
            continue
        # 0 no, 1 marginal, 2 good — ParaglidingEarth's own scale, kept rather than
        # flattened to a boolean: "marginal" is a real answer about a takeoff.
        winds = [int(properties.get(point) or 0) for point in OCTANTS]
        if not any(winds):
            # A takeoff with no direction recorded cannot be judged against the wind,
            # and judging it anyway would be the page's one unforgivable error.
            winds = []
        sites.append({
            "name": name,
            "lat": round(float(lat), 4),
            "lon": round(float(lon), 4),
            "alt": int(float(properties.get("takeoff_altitude") or 0)),
            "winds": winds,
            "id": int(properties.get("pge_site_id") or 0),
        })
    sites.sort(key=lambda site: site["name"].lower())
    return sites


def write(path: Path, sites: list[dict], iso: str = "CZ") -> None:
    """Rewrite `sites.py` from a fetch, provenance first."""
    today = dt.date.today().isoformat()
    lines = [
        '"""Paragliding takeoffs, as committed data.',
        "",
        f"Generated by `meteo.sources.write` from ParaglidingEarth on {today}:",
        f"    {ENDPOINT.format(iso=iso)}",
        "",
        "`winds` is ParaglidingEarth's own suitability per octant, N first and clockwise:",
        "0 unflyable, 1 marginal, 2 good. An empty list means the site records none, and",
        "the page then refuses to judge it against the forecast rather than guessing.",
        '"""',
        "",
        f'SOURCE = "{ENDPOINT.format(iso=iso)}"',
        f'FETCHED = "{today}"',
        f'ATTRIBUTION = "{ATTRIBUTION}"',
        'OCTANTS = ("N", "NE", "E", "SE", "S", "SW", "W", "NW")',
        "",
        "SITES = [",
    ]
    for site in sites:
        lines.append(
            f'    {{"name": {site["name"]!r}, "lat": {site["lat"]}, '
            f'"lon": {site["lon"]}, "alt": {site["alt"]}, '
            f'"winds": {site["winds"]}, "id": {site["id"]}}},'
        )
    lines.append("]")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
